# Generated by Django 4.2 on 2025-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
