# Generated by Django 4.2 on 2025-06-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='scheduled_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
